/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gems;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Shoaib
 */
public class EmployeeADD extends javax.swing.JFrame {

    /**
     * Creates new form Add
     */
    public EmployeeADD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        Search_bar = new javax.swing.JTextField();
        jTextFieldFName2 = new javax.swing.JTextField();
        jTextFieldFName3 = new javax.swing.JTextField();
        jTextFieldFName4 = new javax.swing.JTextField();
        jTextFieldFName5 = new javax.swing.JTextField();
        jTextFieldFName6 = new javax.swing.JTextField();
        jTextFieldFName7 = new javax.swing.JTextField();
        jTextFieldFName9 = new javax.swing.JTextField();
        jTextFieldFName10 = new javax.swing.JTextField();
        create = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        dob = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 240, 241));
        jLabel5.setText("First name:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(236, 240, 241));
        jLabel6.setText("Banking Acc:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 580, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(236, 240, 241));
        jLabel7.setText("Mobile Banking Acc :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 510, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(236, 240, 241));
        jLabel8.setText("Last name:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(236, 240, 241));
        jLabel9.setText("NID :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 570, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(236, 240, 241));
        jLabel10.setText("Gender :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 430, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(236, 240, 241));
        jLabel11.setText("Date of Birth :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(236, 240, 241));
        jLabel12.setText(" Address :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 300, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(236, 240, 241));
        jLabel13.setText("Phone No :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 360, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 255, 0));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField1.setText("Add New Employee");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        back.setText("Return");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Search:");

        Search_bar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_barActionPerformed(evt);
            }
        });
        Search_bar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Search_barKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(back)
                .addGap(658, 658, 658)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(396, 396, 396)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Search_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1900, -1));

        jTextFieldFName2.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldFName2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldFName2.setForeground(new java.awt.Color(236, 240, 241));
        jPanel1.add(jTextFieldFName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 322, 40));

        jTextFieldFName3.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldFName3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldFName3.setForeground(new java.awt.Color(236, 240, 241));
        jPanel1.add(jTextFieldFName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 500, 322, 40));

        jTextFieldFName4.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldFName4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldFName4.setForeground(new java.awt.Color(236, 240, 241));
        jPanel1.add(jTextFieldFName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 580, 322, 40));

        jTextFieldFName5.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldFName5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldFName5.setForeground(new java.awt.Color(236, 240, 241));
        jPanel1.add(jTextFieldFName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 430, 322, 40));

        jTextFieldFName6.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldFName6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldFName6.setForeground(new java.awt.Color(236, 240, 241));
        jPanel1.add(jTextFieldFName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 350, 322, 40));

        jTextFieldFName7.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldFName7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldFName7.setForeground(new java.awt.Color(236, 240, 241));
        jPanel1.add(jTextFieldFName7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 324, 40));

        jTextFieldFName9.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldFName9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldFName9.setForeground(new java.awt.Color(236, 240, 241));
        jPanel1.add(jTextFieldFName9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 560, 322, 40));

        jTextFieldFName10.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldFName10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldFName10.setForeground(new java.awt.Color(236, 240, 241));
        jPanel1.add(jTextFieldFName10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 290, 322, 40));

        create.setBackground(new java.awt.Color(242, 38, 19));
        create.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        create.setText("CREATE");
        create.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createMouseClicked(evt);
            }
        });
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        jPanel1.add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 710, 108, 38));

        cancel.setBackground(new java.awt.Color(242, 38, 19));
        cancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancel.setText("CANCEL");
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 710, 108, 38));
        jPanel1.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 320, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 930, 110, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Employee List");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 930, 160, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 24, 1896, 1044));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        EmployeeList m=new EmployeeList();
        m.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        EmployeeUpdate m=new EmployeeUpdate();
        m.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed

        jTextFieldFName10.setText("");
        jTextFieldFName2.setText("");
        jTextFieldFName3.setText("");
        jTextFieldFName4.setText("");
        jTextFieldFName5.setText("");
        jTextFieldFName6.setText("");
        jTextFieldFName7.setText("");

        jTextFieldFName9.setText("");
    }//GEN-LAST:event_cancelActionPerformed

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelMouseClicked

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed

        String First_Name=jTextFieldFName2.getText();
        String Last_Name=jTextFieldFName7.getText();
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        String date=sdf.format(dob.getDate());
        //String Date_of_Birth=jTextFieldFName1.getText();
        String NID=jTextFieldFName9.getText();
        String Address=jTextFieldFName10.getText();
        String phone_Number=jTextFieldFName6.getText();
        String Gender=jTextFieldFName5.getText();
        String Mobile_Banking_Account=jTextFieldFName3.getText();
        String Banking_Account=jTextFieldFName4.getText();

        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=GEMS;selectMethod=cursor;" + "encrypt=true;trustServerCertificate=true;", "sa", "123456");
            String query = "insert into Employee(First_Name,Last_Name,Date_of_Birth,NiD,Address,phone_Number,Gender,Mobile_Banking_Account,Banking_Account)values(?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst=con.prepareStatement(query);

            pst.setString(1,jTextFieldFName2.getText());
            pst.setString(2,jTextFieldFName7.getText());
            pst.setString(3,date);
            pst.setString(4,jTextFieldFName9.getText());
            pst.setString(5,jTextFieldFName10.getText());
            pst.setString(6,jTextFieldFName6.getText());
            pst.setString(7,jTextFieldFName5.getText());
            pst.setString(8,jTextFieldFName3.getText());
            //if(jTextFieldFName3.getText()=="")pst.setString(8,"null");
            pst.setString(9,jTextFieldFName4.getText());
            //if(jTextFieldFName4.getText()=="")pst.setString(9,"null");

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Inserted successfully!");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Inserted unsuccessfully!");
            System.out.println(e);
        }

    }//GEN-LAST:event_createActionPerformed

    private void createMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createMouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_createMouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        MainForm m=new MainForm();
        m.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void Search_barActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_barActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Search_barActionPerformed

    private void Search_barKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Search_barKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_Search_barKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeADD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeADD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeADD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeADD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeADD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Search_bar;
    private javax.swing.JButton back;
    private javax.swing.JButton cancel;
    private javax.swing.JButton create;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldFName10;
    private javax.swing.JTextField jTextFieldFName2;
    private javax.swing.JTextField jTextFieldFName3;
    private javax.swing.JTextField jTextFieldFName4;
    private javax.swing.JTextField jTextFieldFName5;
    private javax.swing.JTextField jTextFieldFName6;
    private javax.swing.JTextField jTextFieldFName7;
    private javax.swing.JTextField jTextFieldFName9;
    // End of variables declaration//GEN-END:variables
}
