/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gems;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import java.sql.*;
import gems.ConnectionProvider;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Hp
 */
public class JobHistory extends javax.swing.JFrame {
DefaultTableModel model;
    /**
     * Creates new form JobHistory
     */
    public JobHistory() {
        initComponents();
        setRecordsToTable();
    }

    public void setRecordsToTable(){
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=GEMS;selectMethod=cursor;" + "encrypt=true;trustServerCertificate=true;", "sa", "123456");
            String query1="SELECT * FROM Job_History";
            PreparedStatement pst=con.prepareStatement(query1);
            ResultSet rs=pst.executeQuery();
        
            while(rs.next()){
                String Employee_Id =rs.getString("Previous_Company");
                String First_Name=rs.getString("Joining_Date");
                String Last_Name=rs.getString("Ending_Date");
                String Date_of_Birth=rs.getString("Designation");
                String NID=rs.getString("Employee_Id");
                String Address=rs.getString("Job_History_Id");
                
                Object[] obj={Employee_Id,First_Name,Last_Name,Date_of_Birth,NID,Address};
                
                model =(DefaultTableModel)jTable1.getModel();
                model.addRow(obj);
                
            }

        }catch(Exception e){
            e.printStackTrace();
        }
    }
    public void search(String str){
        model = (DefaultTableModel) jTable1.getModel();
        TableRowSorter<DefaultTableModel> trs =new TableRowSorter<>(model);
        jTable1.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Search_bar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnInsert = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnDesignation = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnjobHid = new javax.swing.JTextField();
        btnEmpID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnJobHistory2 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        btnInsert1 = new javax.swing.JButton();
        btnInsert2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 51, 255));
        jLabel1.setFont(new java.awt.Font("Dubai Medium", 1, 36)); // NOI18N
        jLabel1.setText("Job History");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(873, 32, 396, 50));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 58, 49));

        Search_bar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_barActionPerformed(evt);
            }
        });
        Search_bar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Search_barKeyReleased(evt);
            }
        });
        jPanel2.add(Search_bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 40, 260, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Search:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 30, 80, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2039, 120));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInsert.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        jPanel3.add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 780, 107, 49));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Ending Date:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 242, 121, 57));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Joining Date:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 127, 121, 57));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel5.setText("Previous Job:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 38, 121, 57));

        btnDesignation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesignationActionPerformed(evt);
            }
        });
        jPanel3.add(btnDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 339, 237, 60));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        jLabel6.setText("Employee ID:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 443, 121, 57));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Designation:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 338, 121, 57));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel8.setText("Job History ID:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 552, 121, 57));

        btnjobHid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjobHidActionPerformed(evt);
            }
        });
        jPanel3.add(btnjobHid, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 553, 237, 60));

        btnEmpID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpIDActionPerformed(evt);
            }
        });
        jPanel3.add(btnEmpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 444, 237, 60));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Previous Company", "Joining Date", "Ending Date", "Designation", "EmployeeID", "Job History ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 1450, 950));

        btnJobHistory2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJobHistory2ActionPerformed(evt);
            }
        });
        jPanel3.add(btnJobHistory2, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 39, 237, 60));
        jPanel3.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 242, 237, 50));
        jPanel3.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 134, 237, 50));

        btnInsert1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnInsert1.setText("Cancel");
        btnInsert1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsert1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnInsert1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 640, -1, 49));

        btnInsert2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnInsert2.setText("Update");
        btnInsert2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsert2ActionPerformed(evt);
            }
        });
        jPanel3.add(btnInsert2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 780, -1, 49));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 125, 1920, 950));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        String a=btnJobHistory2.getText();
        //String Last_Name=jTextFieldFName7.getText();
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        String date=sdf.format(jDateChooser2.getDate());
        SimpleDateFormat sdf1=new SimpleDateFormat("yyyy-MM-dd");
        String date1=sdf1.format(jDateChooser1.getDate());
        //String Date_of_Birth=jTextFieldFName1.getText();
        String b=btnDesignation.getText();
        String c=btnEmpID.getText();
        String d=btnjobHid.getText();
        //String Gender=jTextFieldFName5.getText();
        //String Mobile_Banking_Account=jTextFieldFName3.getText();
        //String Banking_Account=jTextFieldFName4.getText();

        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=GEMS;selectMethod=cursor;" + "encrypt=true;trustServerCertificate=true;", "sa", "123456");
            String query = "insert into Job_History(Previous_Company,Joining_Date,Ending_Date,Designation,Employee_Id,Job_History_Id)values(?,?,?,?,?,?)";
            PreparedStatement pst=con.prepareStatement(query);

            pst.setString(1,btnJobHistory2.getText());
            pst.setString(2,date);
            pst.setString(3,date1);
            pst.setString(4,btnDesignation.getText());
            pst.setString(5,btnEmpID.getText());
            pst.setString(6,btnjobHid.getText());
            //pst.setString(7,jTextFieldFName5.getText());
           // pst.setString(8,jTextFieldFName3.getText());
            //if(jTextFieldFName3.getText()=="")pst.setString(8,"null");
            //pst.setString(9,jTextFieldFName4.getText());
            //if(jTextFieldFName4.getText()=="")pst.setString(9,"null");

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Inserted successfully!");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Inserted unsuccessfully!");
            System.out.println("notconnect");
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnDesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesignationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDesignationActionPerformed

    private void btnjobHidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjobHidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnjobHidActionPerformed

    private void btnEmpIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEmpIDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MainForm m=new MainForm();
        m.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnJobHistory2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJobHistory2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJobHistory2ActionPerformed

    private void btnInsert1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsert1ActionPerformed
        // TODO add your handling code here:
        btnJobHistory2.setText("");
        //jDateChooser2.setDate();
        //jTextFieldFName3.setText("");
        btnDesignation.setText("");
        btnEmpID.setText("");
        btnjobHid.setText("");
        //jTextFieldFName7.setText("");

        //jTextFieldFName9.setText("");
        
    }//GEN-LAST:event_btnInsert1ActionPerformed

    private void btnInsert2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsert2ActionPerformed
        // TODO add your handling code here:
        JobHistoryUpdate m=new JobHistoryUpdate();
        m.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnInsert2ActionPerformed

    private void Search_barActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_barActionPerformed
        // TODO add your handling code here:
        String searchString=Search_bar.getText();
        search(searchString);
    }//GEN-LAST:event_Search_barActionPerformed

    private void Search_barKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Search_barKeyReleased
        // TODO add your handling code here:
        String searchString=Search_bar.getText();
        search(searchString);
    }//GEN-LAST:event_Search_barKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JobHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JobHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JobHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JobHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JobHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Search_bar;
    private javax.swing.JTextField btnDesignation;
    private javax.swing.JTextField btnEmpID;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnInsert1;
    private javax.swing.JButton btnInsert2;
    private javax.swing.JTextField btnJobHistory2;
    private javax.swing.JTextField btnjobHid;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
