/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gems;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author MUSFIQ
 */
public class MainForm extends javax.swing.JFrame {
DefaultTableModel model;
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setRecordsToTable();
    }
     public void setRecordsToTable(){
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=GEMS;selectMethod=cursor;" + "encrypt=true;trustServerCertificate=true;", "sa", "123456");
            String query1="SELECT * FROM Employee";
            PreparedStatement pst=con.prepareStatement(query1);
            ResultSet rs=pst.executeQuery();
            
            while(rs.next()){
                String Employee_Id =rs.getString("Employee_Id");
                String First_Name=rs.getString("First_Name");
                String Last_Name=rs.getString("Last_Name");
                String Date_of_Birth=rs.getString("Date_of_Birth");
                String NID=rs.getString("NID");
                String Address=rs.getString("Address");
                String Phone_Number=rs.getString("Phone_Number");
                String Gender=rs.getString("Gender");
                String Mobile_Banking_Account=rs.getString("Mobile_Banking_Account");
                String Banking_Account=rs.getString("Banking_Account");
                Object[] obj={Employee_Id,First_Name,Last_Name,Date_of_Birth,NID,Address,Phone_Number,Gender,Mobile_Banking_Account,Banking_Account};
                
                model =(DefaultTableModel)jTable1.getModel();
                model.addRow(obj);
                
            }

        }catch(Exception e){
            e.printStackTrace();
        }
    }
     public void search(String str){
        model = (DefaultTableModel) jTable1.getModel();
        TableRowSorter<DefaultTableModel> trs =new TableRowSorter<>(model);
        jTable1.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hgj = new javax.swing.JLabel();
        btnEmployee = new javax.swing.JButton();
        btnDepartment = new javax.swing.JButton();
        btnJobHistory = new javax.swing.JButton();
        btnSalary = new javax.swing.JButton();
        btnLeave = new javax.swing.JButton();
        btnAllowence = new javax.swing.JButton();
        btnAttendance = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Search = new javax.swing.JLabel();
        Search_bar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(204, 204, 204));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(0, 0, 104));
        sidePanel.setPreferredSize(new java.awt.Dimension(130, 600));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        sidePanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 930, 100, 40));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("   Job History");
        sidePanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 80, -1));

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("    Salary");
        sidePanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, 60, -1));

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("     Leave ");
        sidePanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 730, 60, 20));

        jLabel14.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Allowence");
        sidePanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 840, 70, 30));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Employee");
        sidePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 80, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Department");
        sidePanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 90, 30));

        hgj.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        hgj.setForeground(new java.awt.Color(255, 255, 255));
        hgj.setText("Attendance");
        sidePanel.add(hgj, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 80, 30));

        btnEmployee.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\OneDrive\\Desktop\\GEMS\\GEMS\\src\\icon\\emp2.jpg")); // NOI18N
        btnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeActionPerformed(evt);
            }
        });
        sidePanel.add(btnEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 40, 40));

        btnDepartment.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\OneDrive\\Desktop\\GEMS\\GEMS\\src\\icon\\Dept.png")); // NOI18N
        btnDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartmentActionPerformed(evt);
            }
        });
        sidePanel.add(btnDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 50, 50));

        btnJobHistory.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\OneDrive\\Desktop\\GEMS\\GEMS\\src\\icon\\JobHistory.png")); // NOI18N
        btnJobHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJobHistoryActionPerformed(evt);
            }
        });
        sidePanel.add(btnJobHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 50, 40));

        btnSalary.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\OneDrive\\Desktop\\GEMS\\GEMS\\src\\icon\\salary2.png")); // NOI18N
        btnSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalaryActionPerformed(evt);
            }
        });
        sidePanel.add(btnSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 50, 40));

        btnLeave.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\OneDrive\\Desktop\\GEMS\\GEMS\\src\\icon\\leave.png")); // NOI18N
        btnLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeaveActionPerformed(evt);
            }
        });
        sidePanel.add(btnLeave, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 670, 40, 40));

        btnAllowence.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\OneDrive\\Desktop\\GEMS\\GEMS\\src\\icon\\Allowence2.png")); // NOI18N
        btnAllowence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllowenceActionPerformed(evt);
            }
        });
        sidePanel.add(btnAllowence, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 780, 50, 50));

        btnAttendance.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\OneDrive\\Desktop\\GEMS\\GEMS\\src\\icon\\Attendance.png")); // NOI18N
        btnAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttendanceActionPerformed(evt);
            }
        });
        sidePanel.add(btnAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 60, 50));

        mainPanel.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 230, 1020));

        headerPanel.setBackground(new java.awt.Color(204, 204, 204));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cancel2.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        headerPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1880, 10, -1, -1));

        Search.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Search.setForeground(new java.awt.Color(0, 0, 0));
        Search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Search.setText("Search:");
        headerPanel.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 90, 30));

        Search_bar.setBackground(new java.awt.Color(204, 204, 255));
        Search_bar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_barActionPerformed(evt);
            }
        });
        Search_bar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Search_barKeyReleased(evt);
            }
        });
        headerPanel.add(Search_bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 460, 30));

        mainPanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 35));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "First Name", "Last Name", "Date of Birth", "NID", "Addrtess", "Phonr Number", "Gender", "M Bank Acc", "Bank Acc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        mainPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 1690, 1020));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void Search_barActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_barActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_barActionPerformed

    private void Search_barKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Search_barKeyReleased
        // TODO add your handling code here:
        String searchString=Search_bar.getText();
        search(searchString);
    }//GEN-LAST:event_Search_barKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LogInPage m=new LogInPage();
        m.setVisible(true);

        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeActionPerformed
        // TODO add your handling code here:
        EmployeeADD em = new EmployeeADD();
        em.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEmployeeActionPerformed

    private void btnJobHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJobHistoryActionPerformed
        // TODO add your handling code here:
        JobHistory jb = new JobHistory();
        jb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnJobHistoryActionPerformed

    private void btnSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalaryActionPerformed
        // TODO add your handling code here:
        salary jb = new salary();
        jb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalaryActionPerformed

    private void btnLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeaveActionPerformed
        // TODO add your handling code here:
        Leave lv = new Leave();
        lv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLeaveActionPerformed

    private void btnAllowenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllowenceActionPerformed
        // TODO add your handling code here:
        Allowance lv = new Allowance();
        lv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAllowenceActionPerformed

    private void btnAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttendanceActionPerformed
        // TODO add your handling code here:
        AttendanceClass dr = new AttendanceClass();
        dr.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnAttendanceActionPerformed

    private void btnDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartmentActionPerformed
        // TODO add your handling code here:
        Department dr = new Department();
        dr.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnDepartmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Search;
    private javax.swing.JTextField Search_bar;
    private javax.swing.JButton btnAllowence;
    private javax.swing.JButton btnAttendance;
    private javax.swing.JButton btnDepartment;
    private javax.swing.JButton btnEmployee;
    private javax.swing.JButton btnJobHistory;
    private javax.swing.JButton btnLeave;
    private javax.swing.JButton btnSalary;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel hgj;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
